"""
Django settings for MarkEd project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
import logging

# Load environment variables
load_dotenv()

# Replace the hardcoded OpenAI key with environment variable
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Near the top with other path configurations
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

# Update log file paths
LOG_FILES = {
    'django': os.path.join(LOG_DIR, 'django.log'),
    'performance': os.path.join(LOG_DIR, 'performance.log'),
    'openai': os.path.join(LOG_DIR, 'openai.log'),
    'error': os.path.join(LOG_DIR, 'error.log')
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-mn%@za%f$ey(j*n!8##bi^)a+s5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_ENV', 'development') == 'development'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,backend').split(',')

SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL', 'asejfia@ed.ac.uk')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'MarkEd',
    'rest_framework',
    'ninja',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware must sit above CommonMiddleware so CORS headers are added
    # to responses (and preflight OPTIONS handled) before anything else.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'MarkEd.api.middleware.AuthMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'MarkEd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR), 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'MarkEd.context_processors.support_email',
            ],
        },
    },
]

WSGI_APPLICATION = 'MarkEd.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Database.
#
# Locally and in the source branches this is MySQL 8 (Unified PRD §12.1). For
# deployment on Render — which offers managed Postgres but not MySQL — set
# DATABASE_URL (e.g. postgres://...) and the app runs Postgres instead, with no
# code changes. When DATABASE_URL is unset, the MySQL configuration below is
# used, so local development and the docker-compose stack are unchanged.
if os.getenv('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=os.getenv('DATABASE_SSL', 'true') == 'true',
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DATABASE_NAME', 'markeddb1'),
            'HOST': os.getenv('DATABASE_HOST', 'localhost'),
            'PORT': 3306,
            'USER': os.getenv('DATABASE_USER', 'root'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', 'new_password'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
            'CONN_MAX_AGE': 60,
            'POOL_OPTIONS': {
                'POOL_SIZE': 20,
                'POOL_TIMEOUT': 30,
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# changed from 'en-us'
LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'UTC'

# Could be set to false to avoid confusion, everyone just sees the standard British date-time formatting.
USE_I18N = True

USE_L10N = True

USE_TZ = True

FORMAT_MODULE_PATH = [
    'MarkEd.formats',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "statics"),
]

# In production, we need a static root for collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') if os.getenv('DJANGO_ENV') == 'production' else None

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'statics/media')

# Emailing
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.yahoo.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

EMAIL_HOST_USER = 'yahoo addresses should work with these settings'
EMAIL_HOST_PASSWORD = 'generate your own'

IS_PRODUCTION = os.getenv('DJANGO_ENV') == 'production'

# --- CORS (SPA on a different origin, e.g. Vercel) -------------------------
# Auth is bearer-token, not cookies, so credentials are NOT needed cross-origin;
# the browser sends the Authorization header, which CORS allows by default.
# List the frontend origin(s) in CORS_ALLOWED_ORIGINS, and/or set
# CORS_ALLOW_VERCEL=true to allow every *.vercel.app preview/production URL.
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://localhost'
    ).split(',') if o.strip()
]
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOWED_ORIGIN_REGEXES = []
if os.getenv('CORS_ALLOW_VERCEL', 'false').lower() == 'true':
    CORS_ALLOWED_ORIGIN_REGEXES.append(
        os.getenv('CORS_VERCEL_REGEX', r'^https://.*\.vercel\.app$')
    )

# --- CSRF / cookies --------------------------------------------------------
# CSRF only matters for the legacy Django template pages; the SPA uses the
# bearer token. Trusted origins come from env so deployment sets its own.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]
CSRF_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_SECURE = IS_PRODUCTION

# Behind Render's proxy, tell Django the original request was HTTPS so secure
# cookies and redirects behave correctly.
if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- Cache (bearer-token store) --------------------------------------------
# Tokens live in the cache. Django 4.2 ships a native Redis backend, so no
# extra dependency is needed. REDIS_URL is provided by Render; locally it
# falls back to the compose redis service.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', os.getenv('REDIS_HOST', 'redis://redis:6379/0')),
    }
}

# How long a bearer token stays valid (seconds).
SESSION_TOKEN_TTL = int(os.getenv('SESSION_TOKEN_TTL', str(60 * 60 * 24 * 7)))


# View entire log
# docker exec marked-backend cat /app/django.log

# Follow log updates
# docker exec marked-backend tail -f /app/django.log

# Determine log file path based on environment
LOG_FILE = '/app/django.log' if os.getenv('DJANGO_ENV') == 'production' else os.path.join(BASE_DIR, 'django.log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_django': {
            'class': 'logging.FileHandler',
            'filename': LOG_FILES['django'],
            'formatter': 'verbose',
        },
        'file_error': {
            'class': 'logging.FileHandler',
            'filename': LOG_FILES['error'],
            'formatter': 'verbose',
            'level': 'ERROR',
        },
        'file_performance': {
            'class': 'logging.FileHandler',
            'filename': LOG_FILES['performance'],
            'formatter': 'verbose',
        },
        'file_openai': {
            'class': 'logging.FileHandler',
            'filename': LOG_FILES['openai'],
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_django', 'file_error'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['file_performance'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'performance': {
            'handlers': ['file_performance', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'openai_api': {
            'handlers': ['file_openai', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Define ASGI application
ASGI_APPLICATION = 'MarkEd.asgi.application'

# Channel layers configuration (using Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.getenv('REDIS_HOST', 'redis://redis:6379/0')],
        },
    },
}

# Ensure Redis is installed and running in your environment
