[mypy]
plugins = mypy_django_plugin.main
ignore_missing_imports = False
check_untyped_defs = False
disallow_untyped_defs = False

[mypy.plugins.django-stubs]
django_settings_module = "MarkEd.settings"