# Generated by Django 4.2.4 on 2026-07-23 23:15

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentTitle', models.CharField(max_length=50)),
                ('assignmentDescription', models.TextField(blank=True, null=True)),
                ('assignmentWebsite', models.URLField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'disabled'), (1, 'enabled')], default=1)),
                ('assignment_type', models.CharField(choices=[('INDIVIDUAL', 'Individual Assignment'), ('GROUP', 'Group Assignment')], default='INDIVIDUAL', max_length=20)),
                ('max_group_size', models.IntegerField(blank=True, help_text='Maximum number of students per group', null=True)),
                ('min_group_size', models.IntegerField(blank=True, help_text='Minimum number of students per group', null=True)),
                ('peer_review_enabled', models.BooleanField(default=False, help_text='Enable peer review for this assignment (INDIVIDUAL or GROUP)')),
                ('reviews_per_student', models.IntegerField(blank=True, help_text='Number of peer reviews each student must complete', null=True)),
                ('review_deadline', models.DateTimeField(blank=True, help_text='Deadline for completing peer reviews', null=True)),
                ('assignment_instructions', models.JSONField(blank=True, help_text='JSON field for URLs of .pdf assignment instructions', null=True)),
                ('is_peer_review_matching_complete', models.BooleanField(default=False, help_text='Whether the process of matching students to peer reviews is complete')),
                ('release_date', models.DateTimeField(blank=True, help_text='Date when the assignment is released to students and students can submit their assignments', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementName', models.CharField(max_length=50)),
                ('markingGuide', models.TextField()),
                ('maxInput', models.FloatField()),
                ('marking_scheme', models.CharField(choices=[('SUM', 'Sum of Subparts'), ('CHOICE', 'Choice between Subparts')], default='SUM', max_length=6)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('marking_scheme', models.CharField(blank=True, choices=[('ADD', 'Additive'), ('SEL', 'Selective')], default='ADD', max_length=3, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='MarkEd.assignment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MarkEd.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('marks', models.FloatField()),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='MarkEd.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('start', models.TextField(blank=True, null=True)),
                ('middle', models.TextField(blank=True, null=True)),
                ('end', models.TextField(blank=True, null=True)),
                ('marks_given', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='MarkEd.course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionDateTime', models.DateTimeField(auto_now_add=True)),
                ('submissionFile', models.URLField(blank=True, help_text='URL of the group submission file', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('submission_version', models.IntegerField(default=1, help_text='Submission version number for grouping files submitted together')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_submissions', to='MarkEd.assignment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='MarkEd.group')),
            ],
            options={
                'ordering': ['-submissionDateTime'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField(default='currently no introduction', max_length=300)),
                ('author', models.CharField(default="authors don't want to show their name", max_length=30)),
                ('icon_address', models.ImageField(upload_to='modules')),
                ('configuration', models.CharField(max_length=3000)),
                ('basic', models.SmallIntegerField(default=1)),
                ('configuration_path', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeerReviewAllocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('group_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviewers', to='MarkEd.groupsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submissionDateTime', models.DateTimeField(auto_now_add=True)),
                ('submissionFile', models.URLField(blank=True, help_text='URL of the submission file', null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='{"start": "", "middle":"", "end": ""}', null=True)),
                ('needModerate', models.BooleanField(default=False)),
                ('needHelp', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Marking'), (2, 'Finished')], default=0)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignmentelement')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNumber', models.CharField(max_length=10, unique=True)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('isValid', models.BooleanField(default=False)),
                ('userProfile', models.ImageField(blank=True, upload_to='profile')),
                ('role', models.CharField(choices=[('A', 'Academic'), ('M', 'Marker'), ('T', 'TA'), ('S', 'Student')], max_length=1)),
                ('password', models.CharField(max_length=100)),
                ('must_change_password', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SelfAssessmentSetting',
            fields=[
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MarkEd.assignment')),
                ('enabled', models.BooleanField(default=False)),
                ('use_checklist', models.BooleanField(default=False)),
                ('use_rubric', models.BooleanField(default=False)),
                ('use_reflection', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('needs_feedback', models.BooleanField(default=False)),
                ('max_score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1)),
                ('configuration', models.CharField(max_length=3000)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('S', 'Start'), ('E', 'End'), ('C', 'Close')], max_length=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='TimeDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('duration', models.DurationField()),
                ('selfDefined', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_td', to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='TagCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'Tag must be greater than 2 characters.')])),
                ('visibility', models.IntegerField(choices=[(1, 'Me only'), (2, 'Markers only'), (3, 'Academics only'), (4, 'Everyone')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
                ('subElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.submissionelement')),
            ],
        ),
        migrations.AddField(
            model_name='submissionelement',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user'),
        ),
        migrations.AddField(
            model_name='submissionelement',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.submission'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user'),
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_multisubmission_allowed', models.SmallIntegerField(default=0)),
                ('maximum_submissions', models.IntegerField()),
                ('is_late_submission', models.IntegerField(default=0)),
                ('file_number', models.IntegerField(default=1)),
                ('files', models.CharField(max_length=3000)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSelfAssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_answers', models.JSONField(blank=True, default=dict)),
                ('rubric_answers', models.JSONField(blank=True, default=dict)),
                ('guided_reflection_answers', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_submissions', to='MarkEd.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_submissions', to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='SavedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Questionpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='questionpapers/')),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReviewComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_text', models.TextField()),
                ('feedback', models.TextField()),
                ('margin_text_top', models.TextField(blank=True)),
                ('margin_text_bottom', models.TextField(blank=True)),
                ('position_data', models.JSONField(help_text='\n    Stores PDF annotation position data in format:\n    {\n        "pageNumber": int,\n        "boundingRect": {\n            "left": float,\n            "top": float,\n            "width": float,\n            "height": float\n        }\n    }\n    ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marker_comment', models.TextField(blank=True, default='', help_text='A comment by a marker to display under the feedback by the reviewer.')),
                ('llm_comment', models.TextField(blank=True, default='', help_text='A comment by the LLM to display under the feedback by the reviewer.')),
                ('llm_comment_dismissed', models.BooleanField(default=False, help_text='Whether the LLM comment has been dismissed by the reviewer.')),
                ('review_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.peerreviewallocation')),
            ],
        ),
        migrations.AddField(
            model_name='peerreviewallocation',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_to_do', to='MarkEd.user'),
        ),
        migrations.AddField(
            model_name='peerreviewallocation',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviewers', to='MarkEd.submission'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, 'Submission is moderate'), (2, 'Submission is help'), (3, 'Submission is added'), (4, 'Deadline left 1 days'), (5, 'Deadline left 2 days'), (6, 'Marks released')], default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'no checked'), (1, 'checked')], default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Markscheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='markschemes/')),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField(choices=[(1, 'Academic'), (2, 'Markers'), (3, 'All')], default=1)),
                ('task', models.IntegerField(choices=[(1, 'Fininsh all tasks'), (2, 'Submission is moderate'), (3, 'Submission is help'), (4, 'Submission is added'), (5, 'Deadline left 1 days'), (6, 'Deadline left 2 days'), (7, 'Deadline left 3 days')], default=1)),
                ('title', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'no send'), (1, 'have send')], default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupWorkspaceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.URLField(blank=True, help_text='URL of the workspace file', null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('submitted', 'Submitted')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('review_time', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_workspace_files', to='MarkEd.assignment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_files', to='MarkEd.group')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_files', to='MarkEd.user')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_workspace_files', to='MarkEd.user')),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='GroupSubmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_file_comments', to='MarkEd.user')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to='MarkEd.groupworkspacefile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='groupsubmission',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_submissions_made', to='MarkEd.user'),
        ),
        migrations.CreateModel(
            name='GroupSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the group set (e.g., 'Midterm Groups', 'Final Project Groups')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the group set', null=True)),
                ('max_group_size', models.IntegerField(default=5, help_text='Maximum number of students per group')),
                ('min_group_size', models.IntegerField(default=2, help_text='Minimum number of students per group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_student_self_assignment', models.BooleanField(default=False, help_text='Allow students to join groups by themselves')),
                ('self_assignment_deadline', models.DateTimeField(blank=True, help_text='Deadline for student self-assignment (leave empty for no deadline)', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sets', to='MarkEd.course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='MarkEd.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='MarkEd.user')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='MarkEd.groupset'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='element',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='MarkEd.submissionelement'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.tag'),
        ),
        migrations.CreateModel(
            name='DismissedLLMFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('llm_feedback', models.TextField(help_text='The LLM feedback that was dismissed')),
                ('original_feedback', models.TextField(help_text='The original feedback that triggered the LLM response')),
                ('context_text', models.TextField(help_text='The surrounding text context')),
                ('user_feedback', models.TextField(blank=True, help_text='Optional user feedback')),
                ('dismiss_reason', models.CharField(choices=[('IMPLEMENTED', 'I have implemented the suggestions'), ('INCORRECT', 'The suggestions are incorrect'), ('NOT_APPLICABLE', 'The suggestions are not applicable'), ('DISAGREE', 'I disagree with the suggestions'), ('OTHER', 'Other reason')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course2Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course2Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canCreateAssignment', models.BooleanField(default=False, help_text='Whether the marker can create assignments for the course or not')),
                ('submissionPermission', models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read'), (2, 'Write')], default=0)),
                ('markingPermission', models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read'), (2, 'Write')], default=0)),
                ('structurePermission', models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read'), (2, 'Write')], default=0)),
                ('teamPermission', models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read'), (2, 'Write')], default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.course')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='group_set',
            field=models.ForeignKey(blank=True, help_text='Group category this assignment draws its groups from (GROUP assignments only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='MarkEd.groupset'),
        ),
        migrations.CreateModel(
            name='SubmissionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='{"start": "", "middle":"", "end": ""}', null=True)),
                ('needModerate', models.BooleanField(default=False)),
                ('needHelp', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Marking'), (2, 'Finished')], default=0)),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_elements', to='MarkEd.criteria')),
                ('marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
                ('selected_elements', models.ManyToManyField(blank=True, to='MarkEd.element')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.submission')),
            ],
            options={
                'unique_together': {('submission', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='SelfAssessmentRubricSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.criteria')),
            ],
            options={
                'unique_together': {('assignment', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='ReflectionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('description', 'Description'), ('feelings', 'Feelings'), ('evaluation', 'Evaluation'), ('analysis', 'Analysis'), ('conclusion', 'Conclusion'), ('action_plan', 'Action Plan')], max_length=20)),
                ('prompt_text', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
            options={
                'unique_together': {('assignment', 'stage')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='peerreviewallocation',
            unique_together={('reviewer', 'submission', 'assignment'), ('reviewer', 'group_submission', 'assignment')},
        ),
        migrations.CreateModel(
            name='GroupSubmissionPersonalAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_score', models.FloatField(help_text='Personal contribution adjustment score (can be positive or negative)')),
                ('adjustment_reason', models.TextField(blank=True, help_text='Reason for the adjustment', null=True)),
                ('adjustment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments_made', to='MarkEd.user')),
                ('group_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_adjustments', to='MarkEd.groupsubmission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_personal_adjustments', to='MarkEd.user')),
            ],
            options={
                'ordering': ['-adjustment_date'],
                'unique_together': {('group_submission', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GroupSubmissionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('needModerate', models.BooleanField(default=False)),
                ('needHelp', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Marking'), (2, 'Finished')], default=0)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.element')),
                ('group_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.groupsubmission')),
                ('marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
            options={
                'unique_together': {('group_submission', 'element')},
            },
        ),
        migrations.CreateModel(
            name='GroupSubmissionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='{"start": "", "middle":"", "end": ""}', null=True)),
                ('needModerate', models.BooleanField(default=False)),
                ('needHelp', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Marking'), (2, 'Finished')], default=0)),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_submission_elements', to='MarkEd.criteria')),
                ('group_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.groupsubmission')),
                ('marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
                ('selected_elements', models.ManyToManyField(blank=True, to='MarkEd.element')),
            ],
            options={
                'unique_together': {('group_submission', 'criteria')},
            },
        ),
        migrations.CreateModel(
            name='GroupSubmissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_submissions', models.IntegerField(default=3)),
                ('is_late_submission_allowed', models.BooleanField(default=False)),
                ('allowed_file_formats', models.CharField(default='pdf,doc,docx', max_length=500)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_submission_configs', to='MarkEd.assignment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_configs', to='MarkEd.group')),
            ],
            options={
                'unique_together': {('group', 'assignment')},
            },
        ),
    ]
