# Generated by Django 3.2.4 on 2021-06-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentTitle', models.CharField(max_length=50)),
                ('assignmentWebsite', models.URLField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementName', models.CharField(max_length=50)),
                ('markingGuide', models.TextField()),
                ('maxInput', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionDateTime', models.DateTimeField(auto_now_add=True)),
                ('submissionFile', models.FileField(upload_to='submission')),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Marking'), (2, 'Finished')], default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNumber', models.CharField(max_length=10, unique=True)),
                ('userName', models.CharField(max_length=100)),
                ('userProfile', models.ImageField(blank=True, upload_to='profile')),
                ('role', models.CharField(choices=[('A', 'Academic'), ('M', 'Marker'), ('T', 'TA'), ('S', 'Student')], max_length=1)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('needModerate', models.BooleanField(default=False)),
                ('needHelp', models.BooleanField(default=False)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignmentelement')),
                ('marker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user'),
        ),
        migrations.CreateModel(
            name='Course2Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Course2Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.course')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.course'),
        ),
    ]
