# Generated by Django 3.2.4 on 2021-06-23 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionelement',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user'),
        ),
    ]
