# Generated by Django 3.2.4 on 2021-06-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0002_alter_submissionelement_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionelement',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionelement',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
