# Generated by Django 4.2.4 on 2026-07-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0002_alter_user_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackBankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('used_count', models.IntegerField(default=0)),
                ('up_count', models.IntegerField(default=0)),
                ('down_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_bank_entries', to='MarkEd.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_bank_entries', to='MarkEd.user')),
            ],
            options={
                'ordering': ['-used_count', '-created_at'],
            },
        ),
    ]
