# Generated by Django 3.2.4 on 2021-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0003_auto_20210623_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionelement',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Marking'), (2, 'Finished')], default=0),
        ),
    ]
