# Generated by Django 4.2.4 on 2026-07-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0003_feedbackbankentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackbankentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='feedbackbankentry',
            name='down_count',
        ),
        migrations.RemoveField(
            model_name='feedbackbankentry',
            name='up_count',
        ),
        migrations.CreateModel(
            name='FeedbackBankReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='MarkEd.feedbackbankentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
            options={
                'unique_together': {('entry', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackBankFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='MarkEd.feedbackbankentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
            options={
                'unique_together': {('entry', 'user')},
            },
        ),
    ]
