# Generated by Django 3.2.4 on 2021-06-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0004_submissionelement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
    ]
