# Generated by Django 3.2.4 on 2021-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0005_remove_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionelement',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
