# Generated by Django 3.2.4 on 2021-06-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0006_alter_submissionelement_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentelement',
            name='maxInput',
            field=models.FloatField(),
        ),
    ]
