# Generated by Django 3.2.4 on 2021-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0007_alter_assignmentelement_maxinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseStatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course2marker',
            name='markingPermission',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read'), (2, 'Write')], default=0),
        ),
        migrations.AddField(
            model_name='course2marker',
            name='structurePermission',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read'), (2, 'Write')], default=0),
        ),
        migrations.AddField(
            model_name='course2marker',
            name='submissionPermission',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read'), (2, 'Write')], default=0),
        ),
        migrations.AddField(
            model_name='course2marker',
            name='teamPermission',
            field=models.IntegerField(choices=[(0, 'No Permission'), (1, 'Read'), (2, 'Write')], default=0),
        ),
    ]
