# Generated by Django 3.2.4 on 2021-07-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0008_auto_20210628_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(default='s2075864@ed.ac.uk', max_length=254),
        ),
    ]
