# Generated by Django 3.2.4 on 2021-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0010_alter_user_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseStatus',
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.IntegerField(choices=[(0, 'disabled'), (1, 'enabled')], default=1),
        ),
    ]
