# Generated by Django 3.2.4 on 2021-08-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0011_auto_20210717_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.IntegerField(choices=[(1, 'Submission is moderate'), (2, 'Submission is help'), (3, 'Submission is added'), (4, 'Deadline left 1 days'), (5, 'Deadline left 2 days')], default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'no checked'), (1, 'checked')], default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField(choices=[(1, 'Academic'), (2, 'Markers'), (3, 'All')], default=1)),
                ('task', models.IntegerField(choices=[(1, 'Fininsh all tasks'), (2, 'Submission is moderate'), (3, 'Submission is help'), (4, 'Submission is added'), (5, 'Deadline left 1 days'), (6, 'Deadline left 2 days'), (7, 'Deadline left 3 days')], default=1)),
                ('title', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'no send'), (1, 'have send')], default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
    ]
