# Generated by Django 4.2.4 on 2024-01-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0012_job_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.IntegerField(choices=[(1, 'Submission is moderate'), (2, 'Submission is help'), (3, 'Submission is added'), (4, 'Deadline left 1 days'), (5, 'Deadline left 2 days'), (6, 'Marks released')], default=1),
        ),
        migrations.CreateModel(
            name='SavedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='Questionpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='questionpapers/')),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Markscheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='markschemes/')),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.feedback')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.tag')),
            ],
        ),
    ]
