# Generated by Django 4.2.4 on 2024-01-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0012_job_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.IntegerField(choices=[(1, 'Submission is moderate'), (2, 'Submission is help'), (3, 'Submission is added'), (4, 'Deadline left 1 days'), (5, 'Deadline left 2 days'), (6, 'Marks released')], default=1),
        ),
    ]
