# Generated by Django 4.2.4 on 2024-01-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0013_feedback_tag_alter_notification_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField()),
                ('assignment_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignmentelement')),
            ],
        ),
    ]
