# Generated by Django 4.2.4 on 2024-01-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0014_feedback_total_marks_questionmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='marks_given',
            field=models.FloatField(default=0),
        ),
    ]
