# Generated by Django 4.2.4 on 2024-01-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0015_feedback_marks_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmark',
            name='assignment_element',
        ),
        migrations.AddField(
            model_name='feedback',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='FeedbackTag',
        ),
        migrations.DeleteModel(
            name='QuestionMark',
        ),
    ]
