# Generated by Django 4.2.4 on 2024-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0017_feedback_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='end',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='middle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='start',
            field=models.TextField(blank=True, null=True),
        ),
    ]
