# Generated by Django 4.2.4 on 2024-01-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0013_alter_notification_subject'),
        ('MarkEd', '0019_feedback_course'),
    ]

    operations = [
    ]
