# Generated by Django 4.2.4 on 2024-01-29 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0020_merge_20240126_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='assignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user'),
        ),
    ]
