# Generated by Django 4.2.4 on 2024-02-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0020_merge_20240126_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_tr', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('type_id', models.CharField(choices=[('S', 'Start'), ('E', 'End')], max_length=1)),
                ('assignment_tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('marker_tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_tr', to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='TimeDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_td', models.IntegerField()),
                ('duration', models.DurationField()),
                ('self_defined', models.BooleanField(default=False)),
                ('assignment_td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('marker_td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_td', to='MarkEd.user')),
            ],
        ),
    ]
