# Generated by Django 4.2.4 on 2024-02-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0021_timerecord_timeduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeduration',
            old_name='assignment_td',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='timeduration',
            old_name='marker_td',
            new_name='marker',
        ),
        migrations.RenameField(
            model_name='timeduration',
            old_name='student_td',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='timerecord',
            old_name='assignment_tr',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='timerecord',
            old_name='marker_tr',
            new_name='marker',
        ),
        migrations.RenameField(
            model_name='timerecord',
            old_name='student_tr',
            new_name='student',
        ),
    ]
