# Generated by Django 4.2.4 on 2024-01-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0021_feedback_assignment_feedback_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='assignment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.submission'),
        ),
    ]
