# Generated by Django 4.2.4 on 2024-02-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0022_rename_assignment_td_timeduration_assignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeduration',
            old_name='self_defined',
            new_name='selfDefined',
        ),
        migrations.RenameField(
            model_name='timerecord',
            old_name='type_id',
            new_name='type',
        ),
    ]
