# Generated by Django 4.2.4 on 2024-01-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0022_remove_feedback_assignment_feedback_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='submission',
        ),
        migrations.AddField(
            model_name='feedback',
            name='element',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='MarkEd.submissionelement'),
        ),
    ]
