# Generated by Django 4.2.4 on 2024-01-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0023_remove_feedback_submission_feedback_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='course',
        ),
    ]
