# Generated by Django 4.2.4 on 2024-02-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0023_rename_self_defined_timeduration_selfdefined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user'),
        ),
    ]
