# Generated by Django 4.2.4 on 2024-02-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0024_remove_feedback_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricAssignmentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementName', models.CharField(max_length=50)),
                ('markingGuide', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.AlterField(
            model_name='submissionelement',
            name='feedback',
            field=models.TextField(blank=True, default='{"start": "", "middle":"", "end": ""}', null=True),
        ),
        migrations.CreateModel(
            name='RubricAssignmentPartElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('score', models.FloatField()),
                ('rubricElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.rubricassignmentelement')),
            ],
        ),
    ]
