# Generated by Django 4.2.4 on 2024-02-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0024_alter_timerecord_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='type',
            field=models.CharField(choices=[('S', 'Start'), ('E', 'End'), ('C', 'Close')], max_length=1),
        ),
    ]
