# Generated by Django 4.2.4 on 2024-03-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0025_rubricassignmentelement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubpartElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subpartName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rubricassignmentpartelement',
            name='rubricElement',
        ),
        migrations.AddField(
            model_name='assignmentelement',
            name='marking_scheme',
            field=models.CharField(choices=[('SUM', 'Sum of Subparts'), ('CHOICE', 'Choice between Subparts')], default='SUM', max_length=6),
        ),
        migrations.DeleteModel(
            name='RubricAssignmentElement',
        ),
        migrations.DeleteModel(
            name='RubricAssignmentPartElement',
        ),
        migrations.AddField(
            model_name='subpartelement',
            name='parent_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subparts', to='MarkEd.assignmentelement'),
        ),
    ]
