# Generated by Django 4.2.4 on 2024-02-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0025_alter_timerecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionelement',
            name='dateUpdated',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-28'),
            preserve_default=False,
        ),
    ]
