# Generated by Django 4.2.4 on 2024-03-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0026_subpartelement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('marking_scheme', models.CharField(choices=[('ADD', 'Additive'), ('SEL', 'Selective')], default='ADD', max_length=6)),
                ('parent_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriteria', to='MarkEd.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('marks', models.FloatField()),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='MarkEd.subcriteria')),
            ],
        ),
    ]
