# Generated by Django 4.2.4 on 2024-03-03 17:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0026_submissionelement_dateupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2, 'Tag must be greater than 2 characters.')])),
                ('visibility', models.IntegerField(choices=[(1, 'Me only'), (2, 'Markers only'), (3, 'Academics only'), (4, 'Everyone')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
                ('subElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.submissionelement')),
            ],
        ),
    ]
