# Generated by Django 4.2.4 on 2024-03-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0027_criteria_subcriteria_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MarkEd.criteria'),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='MarkEd.assignment'),
        ),
    ]
