# Generated by Django 4.2.4 on 2024-03-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0028_criteria_parent_alter_criteria_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, default='{"start": "", "middle":"", "end": ""}', null=True)),
                ('needModerate', models.BooleanField(default=False)),
                ('needHelp', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Marking'), (2, 'Finished')], default=0)),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_elements', to='MarkEd.criteria')),
                ('marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
                ('selected_elements', models.ManyToManyField(blank=True, to='MarkEd.element')),
                ('sub_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_elements', to='MarkEd.subcriteria')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.submission')),
            ],
            options={
                'unique_together': {('submission', 'criteria', 'sub_criteria')},
            },
        ),
    ]
