# Generated by Django 4.2.4 on 2024-03-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0029_submissioncriteria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submissioncriteria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='element',
            name='sub_criteria',
        ),
        migrations.AddField(
            model_name='criteria',
            name='marking_scheme',
            field=models.CharField(blank=True, choices=[('ADD', 'Additive'), ('SEL', 'Selective')], default='ADD', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='MarkEd.criteria'),
        ),
        migrations.AlterField(
            model_name='submissioncriteria',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_elements', to='MarkEd.criteria'),
        ),
        migrations.AlterUniqueTogether(
            name='submissioncriteria',
            unique_together={('submission', 'criteria')},
        ),
        migrations.RemoveField(
            model_name='submissioncriteria',
            name='sub_criteria',
        ),
        migrations.DeleteModel(
            name='SubCriteria',
        ),
    ]
