# Generated by Django 4.2.4 on 2024-03-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0030_alter_submissioncriteria_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubpartElement',
        ),
    ]
