# Generated by Django 4.2.4 on 2024-06-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0027_tagcustom'),
        ('MarkEd', '0031_element_name_delete_subpartelement'),
    ]

    operations = [
    ]
