# Generated by Django 4.2.4 on 2024-08-08 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0032_merge_20240614_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduction', models.TextField(default='currently no introduction', max_length=300)),
                ('author', models.CharField(default="authors don't want to show their name", max_length=30)),
                ('icon_address', models.ImageField(upload_to='modules')),
                ('configuration', models.CharField(max_length=300)),
                ('basic', models.SmallIntegerField(default=1)),
                ('configuration_path', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1)),
                ('configuration', models.CharField(max_length=300)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_multisubmission_allowed', models.SmallIntegerField(default=0)),
                ('maximum_submissions', models.IntegerField()),
                ('allowed_file_format', models.CharField(max_length=300)),
                ('file_name', models.CharField(max_length=100)),
                ('is_late_submission', models.IntegerField(default=0)),
                ('file_number', models.IntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
    ]
