# Generated by Django 4.2.4 on 2024-08-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0033_module_usermodule_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='file_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='configuration',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='usermodule',
            name='configuration',
            field=models.CharField(max_length=3000),
        ),
    ]
