# Generated by Django 4.2.4 on 2024-08-10 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0034_studentsubmission_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodule',
            name='assignment',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment'),
        ),
    ]
