# Generated by Django 4.2.4 on 2024-08-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0035_usermodule_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='allowed_file_format',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='file_size',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='files',
            field=models.CharField(default={}, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodule',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment'),
        ),
    ]
