# Generated by Django 4.2.4 on 2024-12-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0036_remove_studentsubmission_allowed_file_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReviewAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Assignment'), ('PEER_REVIEW', 'Peer Review Assignment')], default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='PeerReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('comment', models.TextField()),
                ('position_data', models.JSONField(help_text='\n    Stores PDF annotation position data in format:\n    {\n        "pageNumber": int,\n        "boundingRect": {\n            "x1": float,\n            "y1": float,\n            "x2": float,\n            "y2": float\n        },\n        "rects": [...]  # For multi-line selections\n    }\n    ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.peerreviewallocation')),
                ('submission_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.studentsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_per_student', models.IntegerField(default=3)),
                ('review_deadline', models.DateTimeField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('review_instructions', models.TextField(blank=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='peerreviewallocation',
            name='peer_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.peerreviewassignment'),
        ),
        migrations.AddField(
            model_name='peerreviewallocation',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_to_do', to='MarkEd.user'),
        ),
        migrations.AddField(
            model_name='peerreviewallocation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviewers', to='MarkEd.submission'),
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.CharField(max_length=3000)),
                ('is_latest', models.BooleanField(default=True)),
                ('s3_keys', models.JSONField(help_text="List of S3 keys for this version's files")),
                ('student_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='MarkEd.studentsubmission')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('student_submission', 'version_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='peerreviewallocation',
            unique_together={('reviewer', 'submission', 'peer_assignment')},
        ),
    ]
