# Generated by Django 4.2.16 on 2024-12-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0037_peerreviewallocation_assignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerreviewassignment',
            name='assignment',
        ),
        migrations.AlterUniqueTogether(
            name='peerreviewallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_instructions',
            field=models.JSONField(blank=True, help_text='JSON field for URLs of .pdf assignment instructions', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='review_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for completing peer reviews', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reviews_per_student',
            field=models.IntegerField(blank=True, help_text='Number of peer reviews each student must complete', null=True),
        ),
        migrations.AddField(
            model_name='peerreviewallocation',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MarkEd.assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='peerreviewallocation',
            unique_together={('reviewer', 'submission', 'assignment')},
        ),
        migrations.DeleteModel(
            name='SubmissionVersion',
        ),
        migrations.RemoveField(
            model_name='peerreviewallocation',
            name='peer_assignment',
        ),
        migrations.DeleteModel(
            name='PeerReviewAssignment',
        ),
    ]
