# Generated by Django 4.2.4 on 2024-12-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0039_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='course2marker',
            name='canCreateAssignment',
            field=models.BooleanField(default=False, help_text='Whether the marker can create assignments for the course or not'),
        ),
    ]
