# Generated by Django 4.2.16 on 2024-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0040_course2marker_cancreateassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignmentDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
