# Generated by Django 4.2.16 on 2024-12-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0041_assignment_assignmentdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionFile',
            field=models.URLField(blank=True, help_text='URL of the submission file', null=True),
        ),
    ]
