# Generated by Django 4.2.16 on 2024-12-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0042_alter_submission_submissionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_peer_review_matching_complete',
            field=models.BooleanField(default=False, help_text='Whether the process of matching students to peer reviews is complete'),
        ),
    ]
