# Generated by Django 4.2.16 on 2024-12-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0043_assignment_is_peer_review_matching_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreviewallocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
