# Generated by Django 4.2.16 on 2025-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0044_alter_peerreviewallocation_id_alter_submission_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peerreviewcomment',
            old_name='comment',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='peerreviewcomment',
            name='submission_file',
        ),
        migrations.AddField(
            model_name='peerreviewcomment',
            name='margin_text_bottom',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peerreviewcomment',
            name='margin_text_top',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='peerreviewcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peerreviewcomment',
            name='position_data',
            field=models.JSONField(help_text='\n    Stores PDF annotation position data in format:\n    {\n        "pageNumber": int,\n        "boundingRect": {\n            "left": float,\n            "top": float,\n            "width": float,\n            "height": float\n        }\n    }\n    '),
        ),
    ]
