# Generated by Django 4.2.16 on 2025-01-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0045_rename_comment_peerreviewcomment_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Date when the assignment is released to students and students can submit their assignments', null=True),
        ),
    ]
