# Generated by Django 4.2.16 on 2025-01-14 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0046_assignment_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
