# Generated by Django 4.2.16 on 2025-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0047_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerreviewcomment',
            name='llm_comment',
            field=models.TextField(blank=True, default='', help_text='A comment by the LLM to display under the feedback by the reviewer.'),
        ),
        migrations.AddField(
            model_name='peerreviewcomment',
            name='llm_comment_dismissed',
            field=models.BooleanField(default=False, help_text='Whether the LLM comment has been dismissed by the reviewer.'),
        ),
        migrations.AddField(
            model_name='peerreviewcomment',
            name='marker_comment',
            field=models.TextField(blank=True, default='', help_text='A comment by a marker to display under the feedback by the reviewer.'),
        ),
    ]
