# Generated by Django 4.2.16 on 2025-01-31 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0048_peerreviewcomment_llm_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedLLMFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('llm_feedback', models.TextField(help_text='The LLM feedback that was dismissed')),
                ('context_text', models.TextField(help_text='The surrounding text context')),
                ('user_feedback', models.TextField(blank=True, help_text='Optional user feedback')),
                ('dismiss_reason', models.CharField(choices=[('IMPLEMENTED', 'I have implemented the suggestions'), ('INCORRECT', 'The suggestions are incorrect'), ('NOT_APPLICABLE', 'The suggestions are not applicable'), ('DISAGREE', 'I disagree with the suggestions'), ('OTHER', 'Other reason')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarkEd.user')),
            ],
        ),
    ]
