# Generated by Django 4.2.16 on 2025-01-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkEd', '0049_dismissedllmfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dismissedllmfeedback',
            name='original_feedback',
            field=models.TextField(default='', help_text='The original feedback that triggered the LLM response'),
            preserve_default=False,
        ),
    ]
